### ISSUE TITLE
Struktur des Moduls festlegen

### ISSUE THREAD

**Issue by kf-fhkoeln** [th-koeln/mi-bachelor-webdevelopment#1]
Die Idee die Christian und Kristian Anfang des Jahres besprochen haben ist:

Abweichend von der bestehenden Modulbeschreibung wird das Modul gegliedert in:

- einen Kurs mit 5 CP, in dem ein professioneller git basierter Entwicklungsprozess durchexerziert wird. Es geht darum die git basierte Kooperation an einem Beispiel einzuüben. Insbesondere
-- Umgang mit Branches 
-- Merge Requests und Review Prozesse
-- Nutzung von Issues
-- Projektplanung
-- Testing
-- Kommunikationsstil (eindeutig aber professionell freundlich)

-  Die verbleibenden 15 CP könnten in5 Kurse a3 CP gegliedert werden. Kandidaten sind
-- Front End Development (CN) evtl. auch 2*3 CP
-- Back End Development
-- Open Data
-- Sicherheit und Datenschutz für Web Anwendungen (Benjamin oder Stefans WPF "Praktische Datensicherheit hijacken?)
-- Full Stack IOS
-- IoT

Zu klären ist noch die PSSO Verwaltung: 
- es muss dann wohl nicht jeder Kurs bestanden sein, saondern das gewichtete Mittel mindestens 4,0?
- 5 feste 3CP-Kurse oder n>5 und Wahlpflicht

**Comment by cnoss** [comment]
Der 5 Cp Kurs ist aus meiner Sicht gut … da mache ich gleich noch ein paar Anpassungen/ Erweiterungen.  Frontend & Backend: gut … bei Open Data tue ich mich doch etwas schwer, weil es das Feld wieder so weit öffnet … Sicherheit: ja, wenn wir das richtige da machen … FullStack Mobile: macht mir Bauchschmerzen, weil auch dadurch das Feld soweit geöffnet wird … IoT: könnte interessant sein

**Comment by cnoss** [comment]
Hands-on Development Prozess (5CP): hier gehen wir sehr praktisch die komplette Prozesskette von der Entwicklungsumgebung bis zum Deployment durch:

- Entwicklungsumgebung: LAMP & Ähnliches, ggf. Docker
- lokale Toolsets: SSH, Editor & Integrations
- Umgebungen: Dev, Stage, Prod
- Version Control: Git & GitHub; Branching; Merge Requests und Review Prozesse
- Organisation der Kollaboration: Planung, Issues, IM Integration, Kommunikationsstil
- Deployment: IaaS(AWS), Paas(Heroku), CI


Die verbleibenden 15 CP könnten in5 Kurse a3 CP gegliedert werden. Kandidaten sind
- Front End Development 1 (3 CP): [Vorschlag zu den Inhalten](https://github.com/th-koeln/mi-bachelor-webdevelopment/wiki/Frontend-Dev-2-(Vorschlag-CN))
- Front End Development 2 (3 CP): [Vorschlag zu den Inhalten](https://github.com/th-koeln/mi-bachelor-webdevelopment/wiki/Frontend-Dev-1-(Vorschlag-CN))
- Back End Development
- Sicherheit und Datenschutz für Web Anwendungen (Benjamin oder Stefans WPF "Praktische Datensicherheit hijacken?): Hier ein [Vorschlag zu den Inhalten](https://github.com/th-koeln/mi-bachelor-webdevelopment/wiki/Sicherheit-(Vorschlag-cn)
- IoT

Zu klären ist noch die PSSO Verwaltung:

es muss dann wohl nicht jeder Kurs bestanden sein, saondern das gewichtete Mittel mindestens 4,0?
5 feste 3CP-Kurse oder n>5 und Wahlpflicht
