### ISSUE TITLE
WD Projekt

### ISSUE THREAD

**Issue by cnoss** [th-koeln/mi-bachelor-webdevelopment#15]
Für das Projekt fände ich es, wie schon ein paar mal besprochen, eigentlich gut, wenn wir ein oder mehrere konkrete Themen/ Problemfelder vorgeben würden. Ich würde den organisatorischen Aufwand gerne möglichst klein halten und hätte nicht den Anspruch/ das Ziel, dass hier zwingend Inhalte aus mehreren Kursen in einem Projekt integriert werden müssen. Mein Vorschlag wäre, dass jeder von uns ein Thema/ Problemfeld vorschlagen kann und wir die verschiedenen  [Themen am 04. Juli](https://th-koeln.github.io/mi-bachelor-webdevelopment/lehrveranstaltungen/overall-kickoff-projekt/) vorstellen würden. Folgende Punkte wären mir wichtig (dürfen aber gerne noch diskutiert werden):

1.  Bearbeitung der Themen in 2er Teams
2. gemeinsame Präsentation der Ergebnisse am Ende der Vorlesungsfreien Zeit
3. sauberer, git-gestützter Workflow
4. kurze(!) Dokumentation des Projekts im git oder GitHub Wiki
5. Projekt muss so vorbereitet sein, dass dritte es problemlos starten/ nutzen/ weiterentwickeln können.

Aus Frontend Dev Perspektive würde ich gerne eine Anwendung im Rahmen des [Cranach Digital Archive](http://lucascranach.org/) vorschlagen. Die Studierenden haben in Screendesign bereits schon einen Design Prototypen dazu gebaut. Darum wäre das schön stringent. Die Anwendung würde ein Indoor Ortung erforderlich machen (die aber auch simuliert werden könnte). Das ließe sich ggf. auch mit iBeacon und Ionic realisieren, wobei dann die Latte schon recht hoch hängen würde. Hier gibt es eine genauere [Projektbeschreibung des Screendesign](https://th-koeln.github.io/mi-bachelor-screendesign/projekt-2018/) Projekts.

**Comment by matboehmer** [comment]
I think its done ;)
