### ISSUE TITLE
Weitere Themen für den Tooling/ Praxisteil

### ISSUE THREAD

**Issue by cnoss** [th-koeln/mi-bachelor-webdevelopment#2]
Was soll/ könnte/ müsste da noch rein außer Kollaboration via Git, Qualitätssicherung & Deployment.

**Comment by slemke** [comment]
**Tools**
* NPM
* ~~Gulp~~
* Webpack (Minify, Bable, Autoprefix, Bundeling, ....)
* Eslint
* Pre-Commit Hooks
* (Typescript)

Hintergründe:
* Wenn man NPM und Webpack drin hat ist Gulp meiner Erfahrung nach mittlerweile überflüssig, da diese bereits alles abdecken und man dadurch nur zusätzliche Abhängigkeiten mit rein holt. Außerdem kann man die Zeit in diesem Modul dann lieber für ein bisschen mehr Webpack verwenden.
* Eslint und pre commit hooks sind meiner meinung nach mittlerweile, gerade in Kombination mit Webpack, mittlerweile Pflicht / Standard (bei neueren / Open Source Projekten). 
* Eslint und pre commit hooks helfen ungemein beim Workflow, welcher ja in diesen Modul besonders vermittelt werden soll.
* Typescript könnte man mit rein nehmen, da es immer beliebter wird. Auf längere Sicht wird es wohl überall drin sein. Die großen Frameworks haben es mittlerweile fast alle und es wird überall dafür Werbung gemacht. Würde ich derzeit optional sehen, aber spätestens ab nächstes Jahr wohl dann ein muss. 

**CSS**
* SASS
* ~~Bulma~~ Bootstrap
* BEM
* [IT CSS](https://www.xfive.co/blog/itcss-scalable-maintainable-css-architecture/)

Hintergründe:
* Bulma sollte meiner Meinung nach durch Bootstrap ersetzt werden. Welche Vorliebe hier man nun hat oder nicht hat sollte da keine Rolle spielen, da diese Frameworks grundsätzlich alle das gleiche können. Bootstrap ist aber nach wie vor Marktführer und am meisten genutzt. So können die Studierenden sich da besser reinfinden, da es genug Ressourcen gibt und sie haben eine gute erste Grundlage in dem Bereich.
* BEM als "component based css" finde ich soweit okay. Wichtig finde ich noch dabei Inhalt wie"[CSS Specificity](https://www.smashingmagazine.com/2007/07/css-specificity-things-you-should-know/)" und IT CSS mit rein zunehmen, da gerade auch in einer Welt voller Komponenten das Cascading immer wieder zu kurz kommt / bei Studierenden für Probleme sorgt.

**SPA**
* React
* Vue

Hintergünde:
* Sind die beiden wichtigsten Frameworks. Ich persönlich würde wohl Vue.js verwenden, da es leichter für den Einstieg ist und mittlerweile immer größerer Beliebtheit erfreut - gerade in Kombination mit GraphQL.
* Die andere Frage ist natürlich immer: was können wir vernünftig supporten? Da wäre glaub ich Vue.js auch die bessere Wahl.

**Testing**
* [Cypress (!!!)](https://www.cypress.io/)
* Mocha
* Chai

Hintergründe:
* Kommt drauf an was man hier machen will. Für einfache Unit Tests reichen Mocha und Chai komplett aus.
* Aber: Da es ja in diesem Modul um Workflow geht (zu dem nun mal auch Automation gehört, sowie DevOps, CI / CD)) wäre hier Cypress besonders interessant / wichtig. Mit Cypress lassen sich E2E Tests schreiben, welche sogar problemlos in einer CI Umgebung deployed werden können. Hier gibt es einige wichtige Unterschiede zu Selenium - allen voran das Cypress auf ein asynchrones Web auslegt ist und man nicht mehr so nen Quatsch wie `timeout(3000)` machen und hoffen muss, das der Test nicht fehlschlägt. Außerdem baut es auf Mocha und Chai auf und verwendet dadurch sogar einiges wieder.

**Sonstiges**
* .editorconfig (Coding Styles)
* Visual Studio Code
* TERMINAL

Hintergründe:
* Gerade um einen einheitlichen Stil / Workflow aufrecht zu erhalten sollte nochmal .editorconfig angesprochen werden (2 spaces vs 4 spaces vs tabs)
* Generell würde ich als Tool / Editorempfehlung VSC mitgeben. Bietet alles was man braucht, man muss nichts nach installieren und schlägt Atom und Co. um Längen. VCS ist die "ideale Kombination zwischen Editor und IDE". Nicht zu viel und nicht zu wenig. Außerdem auch plattformunabhängig. 
* Gerade bei Tools sollte das Thema Terminal nochmal auftauchen. Man hat in GDW wieder deutlich gesehen das sich die Leute versuchen daran vorbei zu mogeln. Entweder landen sie ihre Dateien direkt auf der Github Seite hoch oder machen am Ende einen riesen Commit. Während des Workshops kommen dann auch immer wieder Fragen nach "wie wechsel ich ein Verzeichnis" auf oder "ich weiß nicht was ich machen soll. bei mir sieht das alles anders aus", obwohl das Terminal nur ein andere Farbe hat.

... das fällt mir zumindest auf die schnelle ein. Bei Bedarf kann ich nochmal bisschen Zeit investieren und rum schauen.

**Comment by slemke** [comment]
Mir fällt gerade noch was zu den Basics auf:

**Client Side Javascript**
* Basics
* DOM Manipulation
* ~~XHR~~ Fetch

Hintergründe:
* Basics sollten mindestens ES6 sein. Um Karl Lagerfeld zu zitieren: "Wer nicht mindestens Arrow Functions nutzt hat die Kontrolle über sein Leben verloren."
* Ich bin mir nicht ganz sicher, ob man XHR noch wegen IE drin lassen sollte. Fetch sollte aber definitiv behandelt werden, da es mittlerweile auch schon ein "Living Standard" ist und Teil von "Modern Javascript" ist.
